tspivey/yugioh-game

- etc/ygopro-core.patch
- readme.md
- requirements.txt
Alot of requirements were missing in the requirements.txt file, and we also didn't mention the patch required to the ygopro-core in order to run this game properly. Both of those things are now in.
> fixing proper setup instructions

- server.py
> sorting player names returned with the who command alphabetically

- duel.py
- server.py
* on tab/tab2, the amount of attached xyz materials will be shown
* when infoing an xyz monster while it is on the field, its xyz materials will be listed too
> showing xyz material information:

- server.py
introduced in the former pull request. sorry for that.
> fixing crashes whenever an xyz monster doesn't have a location

- duel.py
- server.py
just some additional message handling
> catching deck shuffle message and notifying players and watchers

- server.py
* when deck editing, showing separate main and extra deck counts in prompt
* when starting a duel, executing only one sql statement instead of one statement per card in deck to determine the deck size limits
* introducing extra deck limits (only a maximum of 15 cards in extra deck are allowed)
> multiple deck improvements

- duel.py
- server.py
* fixed counters on spell/trap cards not shown on tab/tab2
* added counter placing/removing messages
> counter support improvements

- duel.py
- server.py
* also fixed the banish message showing the card names even when they got banished face-down
fixes #43
> almost all messages return the remaining data now

- locale/de/LC_MESSAGES/game.po
- server.py
* added new utility function guess_players(name, self), which guesses all players based on the name entered
* already used this function in duel requests, watch commands and tell commands
* ignore command won't use this function for security reasons (ignoring the wrong person due to wrong spelling of account names)
> added internal autocompletion for player names

- server.py
> fixed wrong object given to the name retrieval method of the card object

- duel.py
> retrieving level information whenever checking cards on the table

- server.py
…here a paused duel broke who, also fixed a bug with afk.
> Refactored who, fixed AFK bug

- duel.py
- locale/de/LC_MESSAGES/game.po
- server.py
alot was added here:
* cards changing owner (one by one and swapping)
* cards returning from the grave and from banishment get extra messages too
* new translations added
fixes #6, #39, #56
> added loads of new movement messages

- duel.py
- locale/de/LC_MESSAGES/game.po
- server.py
* idle effects and chained effects are now unlimited, means you can use all effects a card has to offer
* if multiple effects are available, they can be accessed by letters a, b, c, d, and so on, e.g. va, vb, vc, ... or s1a, s1b, s1c... and so on
* if effect descriptions are available in the database, they will be shown as well
* fixed showing level as 0 when xyz monsters are at the table
> Improved effect handling

- server.py
Add g (go) command to deck editor. G followed by a number, as shown in the output of the L command, will jump to that card.
> Add g command for deck editor

- server.py
You can pass "duel", "watch" and/or "idle" to "who" to filter the list by those criteria.
> Add duel, watch and idle filters for who command

- locale/de/LC_MESSAGES/game.po
- ygo/deck_editor.py
- ygo/duel.py
This pr fixes #62, as well as #55.
It adds a deck list count on top of deck list command result, as well as information whos turn it currently is to the score command.
> Deck list count and enhanced score command

- locale/de/LC_MESSAGES/game.po
- ygo/message_handlers/battle.py
- ygo/parsers/lobby_parser.py
- ygo/room.py
> duel room improvements

- locale/de/LC_MESSAGES/game.po
- ygo/deck_editor.py
- ygo/duel.py
- ygo/message_handlers/battle_attack.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/room_parser.py
- ygo/player.py
E.g. fixing crashes whenever cards are in decks which aren't in the current database anymore, or heavily reducing workload and sql overhead when executing score command.
See commit list below.
> several additions and fixes

- server.py
Deck soarting now soarts deck list into monsters, spells, traps, extras. There may be some tuning on this, but it would be nice to get it out and let people test. Also refactored some of the code and updated removal to work with the newly ordered lists. Also added a removal message so you know when you remove a card from your deck (not that it wasn't always obvious).
> Added deck sorting

- ygo/parsers/duel_parser.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/login_parser.py
several stuff, like whole team shown on tab/tab2 command for watchers, or parser problems when reconnecting with old connection still alive
> few tag duel fixes

- ygo/deck_editor.py
- ygo/server.py
instead of executing 2 or 3 sql queries for each card we search through, we will now only require one query per search
> drastically improved search in deck editor

- ygo/channels/watchers.py
fixed watchers channel not showing any messages.
> watchers channel

- ygo/duel.py
- ygo/parsers/lobby_parser.py
watch <player> will now really watch this player instead of always watching player 0.
> fixed always watching player 0

- ygo/channels/tag.py
- ygo/duel.py
- ygo/parsers/duel_parser.py
tag teams now have the tag channel to communicate (tag <text> and taghistory commands)
> tag channels for players

- ygo/duel.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/room_parser.py
- ygo/room.py
Define lifepoints of each team to use on room creation time.
> change lifepoints of teams

- ygo/deck_editor.py
- ygo/parsers/deck_editor_parser.py
- ygo/parsers/room_parser.py
we now got a parser for deck editor commands so we don't need to do this via Reader anymore.
Fixed stuff besides that:
* cards now sorted the same way, no matter how often they are in the deck.
* room parser now uses the same method to display all banlists in the game as the deck editor does
* showing total amount of monsters/spells/traps/extra cards in deck editor list command
> deck editor refactoring

- ygo.py
- ygo/deck_editor.py
- ygo/server.py
- ygo/utils.py
> fixed search with non-ascii characters

- ygo/parsers/deck_editor_parser.py
- ygo/parsers/lobby_parser.py
> made all lobby parser commands available in deck editor parser too

- ygo/duel.py
> fixed wrong player announcement in certain cases

- locale/de/LC_MESSAGES/game.po
- ygo/deck_editor.py
- ygo/parsers/deck_editor_parser.py
- ygo/server.py
fixes #127
make sure to squash this pr in, creates some unnecessary commits.
> fixed cards with multiple versions

- ygo/language_handler.py
- ygo/server.py
> fixed reloadlanguages not reloading the known card ids internally

- locale/it/strings.conf
- readme.md
- requirements.txt
- ygo/duel.py
- ygo/duel_reader.py
- ygo/message_handlers/phase.py
- ygo/message_handlers/yesno.py
show default message whenever a yes/no question without text pops up (closes #140)
fix duel readers showing up after giving up, requiring the player to log off and on again to fix
update to lua 5.3 (note in the readme)
now requiring a special commit of gsb, since the new ones will break our current state
> several small fixes

- locale/de/LC_MESSAGES/game.po
- ygo/channel.py
- ygo/channels/challenge.py
- ygo/duel.py
- ygo/message_handlers/card_hint.py
- ygo/message_handlers/select_unselect_card.py
added new message handler for MSG_SELECT_UNSELECT_CARD as used by link summons and fixed element saber support as well as string formatting crashes in channels
> new message handler and bug fixes

- etc/ygopro-core.patch
- readme.md
- requirements.txt
adaption to newest ygopro-core changes, custom lua builds and twisted/service_identity with attrs
> build fixes

- locale/de/LC_MESSAGES/game.po
- ygo/banlist.py
- ygo/card.py
- ygo/deck_editor.py
- ygo/exceptions.py
- ygo/parsers/room_parser.py
* added remove command in rooms to boot players
* reworked banlist checking / alias checking for better performance and fixed a bug
> remove command in rooms and banlist

- locale/de/LC_MESSAGES/game.po
- ygo/banlist.py
- ygo/message_handlers/chaining.py
> chaining handler now shows card location

- locale/de/LC_MESSAGES/game.po
- locale/de/help/deck
- locale/de/motd.txt
- locale/en/help/deck
- ygo/banlist.py
- ygo/parsers/lobby_parser.py
added a banlist command:
* without arguments: will list all available banlists
* with argument: will list all cards forbidden/limited/semi-limited by this banlistt in alphabetic order
> banlist command

- locale/de/LC_MESSAGES/game.po
- locale/de/help/duell
- locale/en/help/dueling
- ygo/duel.py
- ygo/invite/invitable.py
- ygo/invite/joinable.py
- ygo/parsers/duel_parser.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/room_parser.py
- ygo/player.py
- ygo/room.py
reworked invitation code and added invite command to invite to duels too (works also with private duels)
> invitations to duels

- ygo/deck_editor.py
- ygo/room.py
deck draw works with the public deck system now.
fixed lockdown when player currently playing rps quits the game.
> two small fixes

- locale/de/LC_MESSAGES/game.po
- locale/de/help/deck
- locale/en/help/deck
- ygo/banlist.py
- ygo/card.py
- ygo/constants.py
- ygo/deck_editor.py
- ygo/duel.py
- ygo/message_handlers/act_on_card.py
- ygo/parsers/duel_parser.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/room_parser.py
- ygo/room.py
fixed almost all newer bugs and added a few things:
issues included:
#192, #193, #195, #196, #197, #198, #199, #200
> bugfixes and enhancements

- locale/ja/LC_MESSAGES/game.po
This pr updates and adds Japanese translation strings for the latest server messages.
The commit only updates game.po.
> Add Japanese translation for the latest server messages

- locale/de/LC_MESSAGES/game.po
- ygo/constants.py
- ygo/deck_editor.py
- ygo/exceptions.py
- ygo/parsers/lobby_parser.py
- ygo/parsers/room_parser.py
mainly merges some methods in DeckEditor internally and splits deck commands to list public and private decks separately, as well as listing only banlist-compatible decks within rooms.
> several improvements to deck list and deck command in rooms

- locale/ja/LC_MESSAGES/game.po
This PR adds some minor fixes and improvements for Japanese l10n.
> Japanese locallization fixes

- locale/ja/LC_MESSAGES/game.po
Fix a Kanji typo
Use better wording for "watch"
> Fix incorrect wording in Japanese translation

- ygo/deck_editor.py
- ygo/models.py
- ygo/parsers/room_parser.py
This pr adds the option to select decks in a duel room by it's id.
Old output:
deck name (banlist)
new output
id: deck name (banlist)
now in addition to using the deck command to select a deck like the following
deck name
deck public/name
you can now also type the id like:
deck id
> Made it possible to select a deck by id

- ygo/deck_editor.py
Moved the id behind the name part when listing decks
> Changed format string of deck list

- ygo/parsers/lobby_parser.py
This pr adds more information to the finger command.
For everyone, if the player they look up is an admin, it will now tell them.
If an admin uses the finger command, they will now be able to see set language and encoding for the player.
> Added admin information to the finger command

- locale/de/motd.txt
- locale/en/help/start
- locale/en/motd.txt
- locale/fr/motd.txt
This pr updates the motd to include the discord server link.
It also removes old no longer needed lines from the motd and help start files
> Updated motd and help files

- ygo/parsers/login_parser.py
- ygo/server.py
Localhost commands are commands that can be executed on the login (nickname) screen, if the user is coming from localhost.
We can always have more, but for now, "shutdown" gracefully shuts down the game.
> We now have localhost commands

- locale/de/strings.conf
- locale/en/strings.conf
- locale/es/strings.conf
- locale/fr/strings.conf
- locale/it/strings.conf
- locale/ja/strings.conf
- locale/pt/strings.conf
- locale/th/strings.conf
- ygo/constants.py
This adds the new illusion type that was recently introduced in to YuGiOh.
As an example of a new Illusion type card, take a look at "nightmare magician"
> Added illusion type
